/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PmbIndexRouteImport } from './routes/pmb.index'
import { Route as FakultasIndexRouteImport } from './routes/fakultas/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PmbLoginRouteImport } from './routes/pmb.login'
import { Route as PmbFormulirRouteImport } from './routes/pmb.formulir'
import { Route as PmbDashboardRouteImport } from './routes/pmb.dashboard'
import { Route as PmbDaftarRouteImport } from './routes/pmb.daftar'
import { Route as HalamanSlugRouteImport } from './routes/halaman.$slug'
import { Route as FakultasSlugRouteImport } from './routes/fakultas/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminPmbCandidatesRouteImport } from './routes/admin.pmb-candidates'
import { Route as AdminPmbBatchesRouteImport } from './routes/admin.pmb-batches'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLecturersRouteImport } from './routes/admin.lecturers'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminFacultiesRouteImport } from './routes/admin.faculties'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PmbIndexRoute = PmbIndexRouteImport.update({
  id: '/pmb/',
  path: '/pmb/',
  getParentRoute: () => rootRouteImport,
} as any)
const FakultasIndexRoute = FakultasIndexRouteImport.update({
  id: '/fakultas/',
  path: '/fakultas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PmbLoginRoute = PmbLoginRouteImport.update({
  id: '/pmb/login',
  path: '/pmb/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PmbFormulirRoute = PmbFormulirRouteImport.update({
  id: '/pmb/formulir',
  path: '/pmb/formulir',
  getParentRoute: () => rootRouteImport,
} as any)
const PmbDashboardRoute = PmbDashboardRouteImport.update({
  id: '/pmb/dashboard',
  path: '/pmb/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PmbDaftarRoute = PmbDaftarRouteImport.update({
  id: '/pmb/daftar',
  path: '/pmb/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const HalamanSlugRoute = HalamanSlugRouteImport.update({
  id: '/halaman/$slug',
  path: '/halaman/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FakultasSlugRoute = FakultasSlugRouteImport.update({
  id: '/fakultas/$slug',
  path: '/fakultas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPmbCandidatesRoute = AdminPmbCandidatesRouteImport.update({
  id: '/pmb-candidates',
  path: '/pmb-candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPmbBatchesRoute = AdminPmbBatchesRouteImport.update({
  id: '/pmb-batches',
  path: '/pmb-batches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLecturersRoute = AdminLecturersRouteImport.update({
  id: '/lecturers',
  path: '/lecturers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/faculties',
  path: '/faculties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pmb-batches': typeof AdminPmbBatchesRoute
  '/admin/pmb-candidates': typeof AdminPmbCandidatesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fakultas/$slug': typeof FakultasSlugRoute
  '/halaman/$slug': typeof HalamanSlugRoute
  '/pmb/daftar': typeof PmbDaftarRoute
  '/pmb/dashboard': typeof PmbDashboardRoute
  '/pmb/formulir': typeof PmbFormulirRoute
  '/pmb/login': typeof PmbLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/fakultas/': typeof FakultasIndexRoute
  '/pmb/': typeof PmbIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pmb-batches': typeof AdminPmbBatchesRoute
  '/admin/pmb-candidates': typeof AdminPmbCandidatesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fakultas/$slug': typeof FakultasSlugRoute
  '/halaman/$slug': typeof HalamanSlugRoute
  '/pmb/daftar': typeof PmbDaftarRoute
  '/pmb/dashboard': typeof PmbDashboardRoute
  '/pmb/formulir': typeof PmbFormulirRoute
  '/pmb/login': typeof PmbLoginRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/fakultas': typeof FakultasIndexRoute
  '/pmb': typeof PmbIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pmb-batches': typeof AdminPmbBatchesRoute
  '/admin/pmb-candidates': typeof AdminPmbCandidatesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/fakultas/$slug': typeof FakultasSlugRoute
  '/halaman/$slug': typeof HalamanSlugRoute
  '/pmb/daftar': typeof PmbDaftarRoute
  '/pmb/dashboard': typeof PmbDashboardRoute
  '/pmb/formulir': typeof PmbFormulirRoute
  '/pmb/login': typeof PmbLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/fakultas/': typeof FakultasIndexRoute
  '/pmb/': typeof PmbIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/blog'
    | '/admin/faculties'
    | '/admin/hero'
    | '/admin/lecturers'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/pages'
    | '/admin/pmb-batches'
    | '/admin/pmb-candidates'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/blog/$slug'
    | '/fakultas/$slug'
    | '/halaman/$slug'
    | '/pmb/daftar'
    | '/pmb/dashboard'
    | '/pmb/formulir'
    | '/pmb/login'
    | '/admin/'
    | '/blog/'
    | '/fakultas/'
    | '/pmb/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/blog'
    | '/admin/faculties'
    | '/admin/hero'
    | '/admin/lecturers'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/pages'
    | '/admin/pmb-batches'
    | '/admin/pmb-candidates'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/blog/$slug'
    | '/fakultas/$slug'
    | '/halaman/$slug'
    | '/pmb/daftar'
    | '/pmb/dashboard'
    | '/pmb/formulir'
    | '/pmb/login'
    | '/admin'
    | '/blog'
    | '/fakultas'
    | '/pmb'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/blog'
    | '/admin/faculties'
    | '/admin/hero'
    | '/admin/lecturers'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/pages'
    | '/admin/pmb-batches'
    | '/admin/pmb-candidates'
    | '/admin/programs'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/blog/$slug'
    | '/fakultas/$slug'
    | '/halaman/$slug'
    | '/pmb/daftar'
    | '/pmb/dashboard'
    | '/pmb/formulir'
    | '/pmb/login'
    | '/admin/'
    | '/blog/'
    | '/fakultas/'
    | '/pmb/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FakultasSlugRoute: typeof FakultasSlugRoute
  HalamanSlugRoute: typeof HalamanSlugRoute
  PmbDaftarRoute: typeof PmbDaftarRoute
  PmbDashboardRoute: typeof PmbDashboardRoute
  PmbFormulirRoute: typeof PmbFormulirRoute
  PmbLoginRoute: typeof PmbLoginRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FakultasIndexRoute: typeof FakultasIndexRoute
  PmbIndexRoute: typeof PmbIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmb/': {
      id: '/pmb/'
      path: '/pmb'
      fullPath: '/pmb/'
      preLoaderRoute: typeof PmbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fakultas/': {
      id: '/fakultas/'
      path: '/fakultas'
      fullPath: '/fakultas/'
      preLoaderRoute: typeof FakultasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pmb/login': {
      id: '/pmb/login'
      path: '/pmb/login'
      fullPath: '/pmb/login'
      preLoaderRoute: typeof PmbLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmb/formulir': {
      id: '/pmb/formulir'
      path: '/pmb/formulir'
      fullPath: '/pmb/formulir'
      preLoaderRoute: typeof PmbFormulirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmb/dashboard': {
      id: '/pmb/dashboard'
      path: '/pmb/dashboard'
      fullPath: '/pmb/dashboard'
      preLoaderRoute: typeof PmbDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmb/daftar': {
      id: '/pmb/daftar'
      path: '/pmb/daftar'
      fullPath: '/pmb/daftar'
      preLoaderRoute: typeof PmbDaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halaman/$slug': {
      id: '/halaman/$slug'
      path: '/halaman/$slug'
      fullPath: '/halaman/$slug'
      preLoaderRoute: typeof HalamanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fakultas/$slug': {
      id: '/fakultas/$slug'
      path: '/fakultas/$slug'
      fullPath: '/fakultas/$slug'
      preLoaderRoute: typeof FakultasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pmb-candidates': {
      id: '/admin/pmb-candidates'
      path: '/pmb-candidates'
      fullPath: '/admin/pmb-candidates'
      preLoaderRoute: typeof AdminPmbCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pmb-batches': {
      id: '/admin/pmb-batches'
      path: '/pmb-batches'
      fullPath: '/admin/pmb-batches'
      preLoaderRoute: typeof AdminPmbBatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lecturers': {
      id: '/admin/lecturers'
      path: '/lecturers'
      fullPath: '/admin/lecturers'
      preLoaderRoute: typeof AdminLecturersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLecturersRoute: typeof AdminLecturersRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPmbBatchesRoute: typeof AdminPmbBatchesRoute
  AdminPmbCandidatesRoute: typeof AdminPmbCandidatesRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLecturersRoute: AdminLecturersRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPmbBatchesRoute: AdminPmbBatchesRoute,
  AdminPmbCandidatesRoute: AdminPmbCandidatesRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogSlugRoute: BlogSlugRoute,
  FakultasSlugRoute: FakultasSlugRoute,
  HalamanSlugRoute: HalamanSlugRoute,
  PmbDaftarRoute: PmbDaftarRoute,
  PmbDashboardRoute: PmbDashboardRoute,
  PmbFormulirRoute: PmbFormulirRoute,
  PmbLoginRoute: PmbLoginRoute,
  BlogIndexRoute: BlogIndexRoute,
  FakultasIndexRoute: FakultasIndexRoute,
  PmbIndexRoute: PmbIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
